name: king_cache
description:
  "Flutter package for caching api data and markdown content to disk and improving app performance. It uses the http package to make api calls and use cache directory to cache data"
version: 0.0.57
homepage: "https://github.com/king-technologies/king_cache"

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  device_info_plus: ^12.3.0
  firebase_analytics: ^12.1.2
  firebase_crashlytics: ^5.0.7
  flutter:
    sdk: flutter
  http: ^1.6.0
  in_app_update: ^4.2.5
  intl: ^0.20.2
  local_auth: ^3.0.0
  logger: ^2.6.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:
